# this file was generated by nixpins (https://github.com/juliamertz/nixpins)
{ fetchFromGitHub, ... }:
{
  inputs = {
    bluegone.url = "github:juliamertz/bluegone";
    nixpins.url = "github:juliamertz/nixpins";
    sddm-rose-pine.url = "github:juliamertz/sddm-rose-pine";
  };
  sources = {
    bluegone = fetchFromGitHub {
      owner = "juliamertz";
      repo = "bluegone";
      rev = "a305a6f226e9d5d49847b7bdb9c1c476164d5337";
      hash = "sha256-BjnzjdkD0EUfl9Q0xKk0SJoKxGdPH7l6+vElioC/tXU=";
    };
    nixpins = fetchFromGitHub {
      owner = "juliamertz";
      repo = "nixpins";
      rev = "a4a853fb82b05514803f66216f4451adc9992cb7";
      hash = "sha256-HwbW3MF1r4cfEmkxcT+HpyjvYDvdHjDjWINiO4Uz48w=";
    };
    sddm-rose-pine = fetchFromGitHub {
      owner = "juliamertz";
      repo = "sddm-rose-pine";
      rev = "5665b3630d4b3ca546cf74e6f0f511d5462f52a7";
      hash = "sha256-QVnydE1NL0S/+4N7dkgjEB3I7DWWs5FHOhY3ovxnaYA=";
    };
  };
}
